language: rust
jobs:
    include:
        - rust: stable
          env: FEATURES=""
        - rust: nightly
          env: FEATURES="--features nightly"

services:
    - memcached

script:
    - cargo check $FEATURES --all --all-targets
    - cargo build $FEATURES
    - cargo test $FEATURES --no-fail-fast
