language: rust
rust: nightly

services:
    - memcached

script:
    - cargo check --features nightly --all --all-targets
    - cargo build --features nightly
    - cargo test --features nightly --no-fail-fast
