[package]
name = "memcached-rs"
version = "0.1.2"
authors = ["Y. T. CHUNG <zonyitoo@gmail.com>"]
description = "A MemCached Library in Rust"
repository = "https://github.com/zonyitoo/memcached-rs"
keywords = ["memcached"]
license = "MIT/Apache-2.0"

[lib]
name = "memcached"

[features]
nightly = []

[dependencies]
byteorder = "^0.4.2"
semver = "^0.2.1"
rand = "^0.3.13"
conhash = "^0.3.0"
log = "^0.3.4"
bufstream = "^0.1.1"

[target.'cfg(unix)'.dependencies]
unix_socket = "^0.5.0"

[dev-dependencies]
env_logger = "*"
